// Package graph is the optional entity-relation layer that sits on top
// of the stigmergic blackboard.
//
// This package is the Pentest-Swarm-AI counterpart to ptagent's
// Graphiti + Neo4j integration (see docs/analysis/ptagent-comparison-report.md
// §8.3). The comparison report explicitly recommends:
//   "I. 用 pgvector + pheromone 已经覆盖大多数场景，仅当需要跨任务
//    知识继承时再引入。"
//
// Translation: the graph layer is a "when-needed" add-on, not a hard
// dependency. To honour that, the package is structured around a
// small `GraphStore` interface with two production-relevant
// implementations:
//
//   1. PostgresGraphStore (default) — runs on the existing
//      pgxpool.Pool. Adds two tables (graph_entities, graph_edges)
//      that reuse pgvector for semantic entity search. Zero new
//      infrastructure.
//
//   2. Neo4jGraphStore (optional) — the file exists and the type
//      satisfies `GraphStore`, but the implementation lives in a
//      driver-agnostic stub plus a build-tag-gated real driver
//      that operators opt into with `go build -tags neo4j`. The
//      default `go build ./...` does NOT pull in the 50MB Neo4j
//      driver. This matches the design philosophy: prove the
//      interface is Neo4j-friendly without forcing Neo4j on users.
//
// The extraction side is a separate `EntityExtractor` interface with
// two implementations:
//
//   - LLMEntityExtractor uses the configured llm.Provider with a
//     strict JSON schema (function-call compatible) so OpenAI /
//     DeepSeek / Claude all return the same shape.
//
//   - RuleBasedExtractor is a deterministic regex / pattern fallback
//     that costs nothing and runs offline. Used for tests, dev mode
//     and as a safety net when the LLM is unavailable.
//
// A `GraphHook` wires the two together so every Finding on the
// blackboard automatically becomes an Episode in the graph. The
// hook composition mirrors the existing AutoEmbedHook pattern in
// internal/swarm/blackboard/embed_hook.go.
//
// Performance: a Finding is on the order of 1 KB; one episode costs
// ~one LLM call (or zero, with the rule-based extractor). For
// realistic campaigns of < 10K findings this stays well within
// Postgres headroom. Operators with a need for higher throughput
// can swap the LLM extractor for a batched backend or replace the
// store with Neo4j without touching any agent code.
package graph

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// DefaultEmbeddingDim is the schema width for the graph_entities.embedding
// pgvector column. It matches the LocalStubEmbedder default (384) and
// the most common small-embedding model dimensionality. Operators
// who want a different width should change this constant and apply
// a custom migration; the schema is regenerated by calling
// PostgresGraphStore.Schema(dim) explicitly.
const DefaultEmbeddingDim = 384

// EntityType enumerates the kind of node in the graph. The set is
// intentionally small — it is the broad taxonomy, not the per-agent
// tag. Agents that need finer-grained types should put them into
// Entity.Properties["subtype"].
const (
	EntityTypeHost      = "Host"      // an IP, hostname or CIDR
	EntityTypeSubdomain = "Subdomain" // a DNS subdomain
	EntityTypeService   = "Service"   // a port + protocol + name tuple
	EntityTypeEndpoint  = "Endpoint"  // an HTTP URL or path
	EntityTypeCVE       = "CVE"       // a CVE id (CVE-YYYY-NNNN)
	EntityTypeCWE       = "CWE"       // a CWE id
	EntityTypeTech      = "Technology" // Wappalyzer-style stack tag
	EntityTypePerson    = "Person"    // an attacker / author / contact
	EntityTypeTool      = "Tool"      // a piece of software (nmap, sqlmap…)
	EntityTypeAgent     = "Agent"     // an LLM agent
	EntityTypeCampaign  = "Campaign"  // a pentest campaign
	EntityTypeFinding   = "Finding"   // a blackboard finding (rare; usually edges are enough)
	EntityTypeSecret    = "Secret"    // a leaked credential / token
	EntityTypeSession   = "Session"   // an active exploit session
)

// RelationType enumerates the edge labels. The label namespace is
// Graphiti-style SCREAMING_SNAKE verbs: a from-node AFFECTS a to-node,
// a Host RUNS_ON a Service, etc.
const (
	RelationAffects    = "AFFECTS"     // e.g. CVE → Service
	RelationRunsOn     = "RUNS_ON"     // e.g. Service → Host
	RelationHosts      = "HOSTS"       // e.g. Host → Subdomain
	RelationExposes    = "EXPOSES"     // e.g. Service → Endpoint
	RelationDetectedBy = "DETECTED_BY" // e.g. Finding → Tool
	RelationExploits   = "EXPLOITS"    // e.g. Exploit → CVE
	RelationTargets    = "TARGETS"     // e.g. Campaign → Host
	RelationProduces   = "PRODUCES"    // e.g. Agent → Finding
	RelationHas        = "HAS"         // generic possession
	RelationRelatesTo  = "RELATES_TO"  // generic association
)

// Entity is a node in the knowledge graph. It carries a coarse
// type (Host / CVE / Service / Person …), a label (the canonical
// name as extracted), an optional embedding (pgvector column),
// and a free-form property bag.
type Entity struct {
	ID         uuid.UUID      `json:"id"`
	Type       string         `json:"type"`
	Label      string         `json:"label"`
	Properties map[string]any `json:"properties,omitempty"`
	CampaignID uuid.UUID      `json:"campaign_id"`
	CreatedAt  time.Time      `json:"created_at"`

	// Embedding is the semantic vector for this entity. Populated
	// when a GraphStore is constructed with an Embedder; nil means
	// "no vector — semantic search will skip this row".
	Embedding []float32 `json:"embedding,omitempty"`
}

// Relation is a typed edge between two entities. The label follows
// Graphiti's `edge_type` convention (SCREAMING_SNAKE_CASE). ValidFrom
// / ValidTo are time-bounded so a fact like "Service A was on port 80
// between T1 and T2" can be expressed; either may be the zero value
// when the edge is point-in-time.
type Relation struct {
	ID         uuid.UUID      `json:"id"`
	FromID     uuid.UUID      `json:"from_id"`
	ToID       uuid.UUID      `json:"to_id"`
	Type       string         `json:"type"`
	Properties map[string]any `json:"properties,omitempty"`
	CampaignID uuid.UUID      `json:"campaign_id"`
	CreatedAt  time.Time      `json:"created_at"`
	ValidFrom  time.Time      `json:"valid_from,omitempty"`
	ValidTo    *time.Time     `json:"valid_to,omitempty"`
}

// Episode is the input unit fed to an EntityExtractor. It is
// intentionally generic — it can wrap a Finding, a tool output, a
// text snippet or anything else that an LLM can mine for entities.
// Source / SourceID are observability hooks (LangFuse spans,
// log lines) so we can trace which input produced which entities.
type Episode struct {
	Source     string    // "finding" / "tool_output" / "manual" / "llm"
	SourceID   string    // Finding.ID.String() or arbitrary ref
	CampaignID uuid.UUID
	Text       string    // what gets sent to the LLM
	OccurredAt time.Time
}

// GraphStore is the persistence interface. Implementations must
// be safe for concurrent use. Errors are opaque to the agent
// layer — the hook treats them as best-effort.
type GraphStore interface {
	// AddEntity upserts an entity. Returns the canonical ID (the
	// same input is deduped to one row per (type, label, campaign)).
	AddEntity(ctx context.Context, e Entity) (uuid.UUID, error)

	// AddRelation upserts a relation. Returns the canonical ID.
	AddRelation(ctx context.Context, r Relation) (uuid.UUID, error)

	// AddEpisode is the convenience write: extract entities /
	// relations via the provided extractor, then persist them in
	// a single transaction. Implementations MAY do the extraction
	// in-line (LLMEntityExtractor is synchronous) or in a worker
	// pool (the rule-based extractor is fast enough either way).
	AddEpisode(ctx context.Context, ep Episode, extractor EntityExtractor) error

	// QueryEntities returns entities matching the query. Filters
	// are AND-combined. NearVector/NearK perform a pgvector
	// cosine search when both are set; nil/0 = skip.
	QueryEntities(ctx context.Context, q EntityQuery) ([]Entity, error)

	// QueryRelations returns relations matching the query. FromID
	// and ToID are independent (an edge is matched if EITHER side
	// matches). Since / Until apply to (ValidFrom, ValidTo) so
	// point-in-time and bifact queries are both expressible.
	QueryRelations(ctx context.Context, q RelationQuery) ([]Relation, error)

	// Traverse does a BFS from startID up to depth hops, returning
	// every reachable entity and the edges traversed.
	Traverse(ctx context.Context, startID uuid.UUID, depth int) (Traversal, error)

	// Stats is for operator dashboards. Implementation may
	// approximate when the table is large; the contract only
	// promises a coherent snapshot.
	Stats(ctx context.Context) (GraphStats, error)

	// Close releases any held resources. Idempotent.
	Close() error
}

// EntityQuery filters entities. All set conditions are AND-combined.
// Limit 0 = implementation default (typically 100).
type EntityQuery struct {
	Type       string     // exact match, "" = no filter
	LabelLike  string     // SQL LIKE, "" = no filter
	CampaignID *uuid.UUID // pointer so nil = no filter
	NearVector []float32  // nil = no vector search
	NearK      int        // 0 = no vector search
	Limit      int
}

// RelationQuery filters relations. All set conditions are AND-combined.
type RelationQuery struct {
	FromID     *uuid.UUID
	ToID       *uuid.UUID
	Type       string
	CampaignID *uuid.UUID
	Since      *time.Time // relation's ValidFrom >= Since
	Until      *time.Time // relation's ValidTo <= Until (NULL = open-ended)
	Limit      int
}

// Traversal is the result of a BFS from a starting entity. Both
// slices are deduplicated by ID. The order is BFS visit order:
// the starting entity is first, and every entity has at least
// one connecting edge in the Relations slice (or the start itself,
// which has no incoming edge).
type Traversal struct {
	Entities  []Entity   `json:"entities"`
	Relations []Relation `json:"relations"`
}

// GraphStats is a dashboard snapshot. Implementations may
// approximate counts when the table is large; the contract
// only requires a consistent per-row snapshot within a single
// call.
type GraphStats struct {
	EntityCount   int            `json:"entity_count"`
	RelationCount int            `json:"relation_count"`
	ByType        map[string]int `json:"by_type"`
	ByCampaign    map[string]int `json:"by_campaign"`
}
